const PLAYER_LIVES = 5;
const RUBBISH_COUNT = 5;
const SLOWEST_RUBBISH_PATH_DURATION = 1000 * 120;
const LIFEBUOY_SPAWN_RATE = 1000 * 10;
const LIFEBUOY_LIVE_DURATION = 1000 * 5;
const LIFEBOUY_EFFECT_DURATION = 3000;
const ARROW_SPEED = 1000;
const HITS_TO_WIN = 6;

const WIN_SERVER_REQUEST = (timeResult) => {
  //AJAX REQUEST HERE
};

const LOSE_SERVER_REQUEST = (timeResult) => {
  //AJAX REQUEST HERE
};
